package com.cursee.new_slab_variants;

import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.SlabBlock;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.properties.NoteBlockInstrument;
import net.minecraft.world.level.material.MapColor;

public class NewSlabsFabric {

    public static final Block DIRT_SLAB;
    public static final Block PODZOL_SLAB;
    public static final Block MYCELIUM_SLAB;
    public static final Block DIRT_PATH_SLAB;
    public static final Block COARSE_DIRT_SLAB;
    public static final Block ROOTED_DIRT_SLAB;
    public static final Block MUD_SLAB;
    public static final Block CLAY_SLAB;
    public static final Block GRAVEL_SLAB;
    public static final Block SAND_SLAB;
    public static final Block SANDSTONE_SLAB;
    public static final Block RED_SAND_SLAB;
    public static final Block RED_SANDSTONE_SLAB;
    public static final Block ICE_SLAB;
    public static final Block PACKED_ICE_SLAB;
    public static final Block BLUE_ICE_SLAB;
    public static final Block SNOW_BLOCK_SLAB;
    public static final Block MOSS_BLOCK_SLAB;
    public static final Block GRANITE_SLAB;
    public static final Block DIORITE_SLAB;
    public static final Block ANDESITE_SLAB;
    public static final Block CRIMSON_NYLIUM_SLAB;
    public static final Block WARPED_NYLIUM_SLAB;
    public static final Block SOUL_SAND_SLAB;
    public static final Block SOUL_SOIL_SLAB;
    public static final Block BONE_BLOCK_SLAB;
    public static final Block BLACKSTONE_SLAB;
    public static final Block CALCITE_SLAB;
    public static final Block TUFF_SLAB;
    public static final Block DRIPSTONE_BLOCK_SLAB;
    public static final Block PRISMARINE_SLAB;
    public static final Block MAGMA_BLOCK_SLAB;
    public static final Block OBSIDIAN_SLAB;
    public static final Block CRYING_OBSIDIAN_SLAB;
    public static final Block BUDDING_AMETHYST_SLAB;
    public static final Block BROWN_MUSHROOM_BLOCK_SLAB;
    public static final Block RED_MUSHROOM_BLOCK_SLAB;
    public static final Block NETHER_WART_BLOCK_SLAB;
    public static final Block WARPED_WART_BLOCK_SLAB;
    public static final Block GLOWSTONE_SLAB;
    public static final Block SHROOMLIGHT_SLAB;
    public static final Block DRIED_KELP_BLOCK_SLAB;
    public static final Block TUBE_CORAL_BLOCK_SLAB;
    public static final Block BRAIN_CORAL_BLOCK_SLAB;
    public static final Block BUBBLE_CORAL_BLOCK_SLAB;
    public static final Block FIRE_CORAL_BLOCK_SLAB;
    public static final Block HORN_CORAL_BLOCK_SLAB;
    public static final Block DEAD_TUBE_CORAL_BLOCK_SLAB;
    public static final Block DEAD_BRAIN_CORAL_BLOCK_SLAB;
    public static final Block DEAD_BUBBLE_CORAL_BLOCK_SLAB;
    public static final Block DEAD_FIRE_CORAL_BLOCK_SLAB;
    public static final Block DEAD_HORN_CORAL_BLOCK_SLAB;
    public static final Block SPONGE_SLAB;
    public static final Block WET_SPONGE_SLAB;
    public static final Block MELON_SLAB;
    public static final Block PUMPKIN_SLAB;
    public static final Block HAY_BALE_SLAB;
    public static final Block HONEYCOMB_BLOCK_SLAB;
    public static final Block SLIME_BLOCK_SLAB;
    public static final Block HONEY_BLOCK_SLAB;
    public static final Block OCHRE_FROGLIGHT_SLAB;
    public static final Block VERDANT_FROGLIGHT_SLAB;
    public static final Block PEARLESCENT_FROGLIGHT_SLAB;
    public static final Block SCULK_SLAB;
    public static final Block BEDROCK_SLAB;


    public static final Block OAK_LOG_SLAB;
    public static final Block OAK_WOOD_SLAB;
    public static final Block STRIPPED_OAK_LOG_SLAB;
    public static final Block STRIPPED_OAK_WOOD_SLAB;
    public static final Block SPRUCE_LOG_SLAB;
    public static final Block SPRUCE_WOOD_SLAB;
    public static final Block STRIPPED_SPRUCE_LOG_SLAB;
    public static final Block STRIPPED_SPRUCE_WOOD_SLAB;
    public static final Block BIRCH_LOG_SLAB;
    public static final Block BIRCH_WOOD_SLAB;
    public static final Block STRIPPED_BIRCH_LOG_SLAB;
    public static final Block STRIPPED_BIRCH_WOOD_SLAB;
    public static final Block JUNGLE_LOG_SLAB;
    public static final Block JUNGLE_WOOD_SLAB;
    public static final Block STRIPPED_JUNGLE_LOG_SLAB;
    public static final Block STRIPPED_JUNGLE_WOOD_SLAB;
    public static final Block ACACIA_LOG_SLAB;
    public static final Block ACACIA_WOOD_SLAB;
    public static final Block STRIPPED_ACACIA_LOG_SLAB;
    public static final Block STRIPPED_ACACIA_WOOD_SLAB;
    public static final Block DARK_OAK_LOG_SLAB;
    public static final Block DARK_OAK_WOOD_SLAB;
    public static final Block STRIPPED_DARK_OAK_LOG_SLAB;
    public static final Block STRIPPED_DARK_OAK_WOOD_SLAB;
    public static final Block MANGROVE_LOG_SLAB;
    public static final Block MANGROVE_WOOD_SLAB;
    public static final Block STRIPPED_MANGROVE_LOG_SLAB;
    public static final Block STRIPPED_MANGROVE_WOOD_SLAB;
    public static final Block CHERRY_LOG_SLAB;
    public static final Block CHERRY_WOOD_SLAB;
    public static final Block STRIPPED_CHERRY_LOG_SLAB;
    public static final Block STRIPPED_CHERRY_WOOD_SLAB;
    public static final Block BAMBOO_BLOCK_SLAB;
    public static final Block STRIPPED_BAMBOO_BLOCK_SLAB;
    public static final Block CRIMSON_STEM_SLAB;
    public static final Block CRIMSON_HYPHAE_SLAB;
    public static final Block STRIPPED_CRIMSON_STEM_SLAB;
    public static final Block STRIPPED_CRIMSON_HYPHAE_SLAB;
    public static final Block WARPED_STEM_SLAB;
    public static final Block WARPED_HYPHAE_SLAB;
    public static final Block STRIPPED_WARPED_STEM_SLAB;
    public static final Block STRIPPED_WARPED_HYPHAE_SLAB;
    public static final Block CRACKED_STONE_BRICKS_SLAB;
    public static final Block CHISELED_STONE_BRICKS_SLAB;
    public static final Block DEEPSLATE_SLAB;
    public static final Block CHISELED_DEEPSLATE_SLAB;
    public static final Block CRACKED_DEEPSLATE_BRICKS_SLAB;
    public static final Block CRACKED_DEEPSLATE_TILES_SLAB;
    public static final Block REINFORCED_DEEPSLATE_SLAB;
    public static final Block PACKED_MUD_SLAB;
    public static final Block CHISELED_SANDSTONE_SLAB;
    public static final Block CHISELED_RED_SANDSTONE_SLAB;
    public static final Block NETHERRACK_SLAB;
    public static final Block CRACKED_NETHER_BRICKS_SLAB;
    public static final Block CHISELED_NETHER_BRICKS_SLAB;
    public static final Block BASALT_SLAB;
    public static final Block SMOOTH_BASALT_SLAB;
    public static final Block POLISHED_BASALT_SLAB;
    public static final Block GILDED_BLACKSTONE_SLAB;
    public static final Block CHISELED_POLISHED_BLACKSTONE_SLAB;
    public static final Block CRACKED_POLISHED_BLACKSTONE_BRICKS_SLAB;
    public static final Block END_STONE_SLAB;
    public static final Block PURPUR_PILLAR_SLAB;
    public static final Block COAL_BLOCK_SLAB;
    public static final Block IRON_BLOCK_SLAB;
    public static final Block GOLD_BLOCK_SLAB;
    public static final Block REDSTONE_BLOCK_SLAB;
    public static final Block EMERALD_BLOCK_SLAB;
    public static final Block LAPIS_BLOCK_SLAB;
    public static final Block DIAMOND_BLOCK_SLAB;
    public static final Block NETHERITE_BLOCK_SLAB;
    public static final Block CHISELED_QUARTZ_BLOCK_SLAB;
    public static final Block QUARTZ_BRICKS_SLAB;
    public static final Block QUARTZ_PILLAR_SLAB;
    public static final Block AMETHYST_BLOCK_SLAB;
    public static final Block COPPER_BLOCK_SLAB;
    public static final Block EXPOSED_COPPER_BLOCK_SLAB;
    public static final Block WEATHERED_COPPER_BLOCK_SLAB;
    public static final Block OXIDIZED_COPPER_BLOCK_SLAB;
    public static final Block WHITE_WOOL_SLAB;
    public static final Block LIGHT_GRAY_WOOL_SLAB;
    public static final Block GRAY_WOOL_SLAB;
    public static final Block BLACK_WOOL_SLAB;
    public static final Block BROWN_WOOL_SLAB;
    public static final Block RED_WOOL_SLAB;
    public static final Block ORANGE_WOOL_SLAB;
    public static final Block YELLOW_WOOL_SLAB;
    public static final Block LIME_WOOL_SLAB;
    public static final Block GREEN_WOOL_SLAB;
    public static final Block CYAN_WOOL_SLAB;
    public static final Block LIGHT_BLUE_WOOL_SLAB;
    public static final Block BLUE_WOOL_SLAB;
    public static final Block PURPLE_WOOL_SLAB;
    public static final Block MAGENTA_WOOL_SLAB;
    public static final Block PINK_WOOL_SLAB;
    public static final Block TERRACOTTA_SLAB;
    public static final Block WHITE_TERRACOTTA_SLAB;
    public static final Block LIGHT_GRAY_TERRACOTTA_SLAB;
    public static final Block GRAY_TERRACOTTA_SLAB;
    public static final Block BLACK_TERRACOTTA_SLAB;
    public static final Block BROWN_TERRACOTTA_SLAB;
    public static final Block RED_TERRACOTTA_SLAB;
    public static final Block ORANGE_TERRACOTTA_SLAB;
    public static final Block YELLOW_TERRACOTTA_SLAB;
    public static final Block LIME_TERRACOTTA_SLAB;
    public static final Block GREEN_TERRACOTTA_SLAB;
    public static final Block CYAN_TERRACOTTA_SLAB;
    public static final Block LIGHT_BLUE_TERRACOTTA_SLAB;
    public static final Block BLUE_TERRACOTTA_SLAB;
    public static final Block PURPLE_TERRACOTTA_SLAB;
    public static final Block MAGENTA_TERRACOTTA_SLAB;
    public static final Block PINK_TERRACOTTA_SLAB;
    public static final Block WHITE_CONCRETE_SLAB;
    public static final Block LIGHT_GRAY_CONCRETE_SLAB;
    public static final Block GRAY_CONCRETE_SLAB;
    public static final Block BLACK_CONCRETE_SLAB;
    public static final Block BROWN_CONCRETE_SLAB;
    public static final Block RED_CONCRETE_SLAB;
    public static final Block ORANGE_CONCRETE_SLAB;
    public static final Block YELLOW_CONCRETE_SLAB;
    public static final Block LIME_CONCRETE_SLAB;
    public static final Block GREEN_CONCRETE_SLAB;
    public static final Block CYAN_CONCRETE_SLAB;
    public static final Block LIGHT_BLUE_CONCRETE_SLAB;
    public static final Block BLUE_CONCRETE_SLAB;
    public static final Block PURPLE_CONCRETE_SLAB;
    public static final Block MAGENTA_CONCRETE_SLAB;
    public static final Block PINK_CONCRETE_SLAB;
    public static final Block WHITE_CONCRETE_POWDER_SLAB;
    public static final Block LIGHT_GRAY_CONCRETE_POWDER_SLAB;
    public static final Block GRAY_CONCRETE_POWDER_SLAB;
    public static final Block BLACK_CONCRETE_POWDER_SLAB;
    public static final Block BROWN_CONCRETE_POWDER_SLAB;
    public static final Block RED_CONCRETE_POWDER_SLAB;
    public static final Block ORANGE_CONCRETE_POWDER_SLAB;
    public static final Block YELLOW_CONCRETE_POWDER_SLAB;
    public static final Block LIME_CONCRETE_POWDER_SLAB;
    public static final Block GREEN_CONCRETE_POWDER_SLAB;
    public static final Block CYAN_CONCRETE_POWDER_SLAB;
    public static final Block LIGHT_BLUE_CONCRETE_POWDER_SLAB;
    public static final Block BLUE_CONCRETE_POWDER_SLAB;
    public static final Block PURPLE_CONCRETE_POWDER_SLAB;
    public static final Block MAGENTA_CONCRETE_POWDER_SLAB;
    public static final Block PINK_CONCRETE_POWDER_SLAB;
    public static final Block WHITE_GLAZED_TERRACOTTA_SLAB;
    public static final Block LIGHT_GRAY_GLAZED_TERRACOTTA_SLAB;
    public static final Block GRAY_GLAZED_TERRACOTTA_SLAB;
    public static final Block BLACK_GLAZED_TERRACOTTA_SLAB;
    public static final Block BROWN_GLAZED_TERRACOTTA_SLAB;
    public static final Block RED_GLAZED_TERRACOTTA_SLAB;
    public static final Block ORANGE_GLAZED_TERRACOTTA_SLAB;
    public static final Block YELLOW_GLAZED_TERRACOTTA_SLAB;
    public static final Block LIME_GLAZED_TERRACOTTA_SLAB;
    public static final Block GREEN_GLAZED_TERRACOTTA_SLAB;
    public static final Block CYAN_GLAZED_TERRACOTTA_SLAB;
    public static final Block LIGHT_BLUE_GLAZED_TERRACOTTA_SLAB;
    public static final Block BLUE_GLAZED_TERRACOTTA_SLAB;
    public static final Block PURPLE_GLAZED_TERRACOTTA_SLAB;
    public static final Block MAGENTA_GLAZED_TERRACOTTA_SLAB;
    public static final Block PINK_GLAZED_TERRACOTTA_SLAB;

    static {
        DIRT_SLAB = registerBlock("dirt_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        PODZOL_SLAB = registerBlock("podzol_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        MYCELIUM_SLAB = registerBlock("mycelium_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        DIRT_PATH_SLAB = registerBlock("dirt_path_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        COARSE_DIRT_SLAB = registerBlock("coarse_dirt_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        ROOTED_DIRT_SLAB = registerBlock("rooted_dirt_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        MUD_SLAB = registerBlock("mud_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CLAY_SLAB = registerBlock("clay_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        GRAVEL_SLAB = registerBlock("gravel_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        SAND_SLAB = registerBlock("sand_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        SANDSTONE_SLAB = registerBlock("sandstone_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        RED_SAND_SLAB = registerBlock("red_sand_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        RED_SANDSTONE_SLAB = registerBlock("red_sandstone_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        ICE_SLAB = registerBlock("ice_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        PACKED_ICE_SLAB = registerBlock("packed_ice_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BLUE_ICE_SLAB = registerBlock("blue_ice_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        SNOW_BLOCK_SLAB = registerBlock("snow_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        MOSS_BLOCK_SLAB = registerBlock("moss_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        GRANITE_SLAB = registerBlock("granite_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        DIORITE_SLAB = registerBlock("diorite_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        ANDESITE_SLAB = registerBlock("andesite_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CRIMSON_NYLIUM_SLAB = registerBlock("crimson_nylium_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        WARPED_NYLIUM_SLAB = registerBlock("warped_nylium_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        SOUL_SAND_SLAB = registerBlock("soul_sand_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        SOUL_SOIL_SLAB = registerBlock("soul_soil_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BONE_BLOCK_SLAB = registerBlock("bone_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BLACKSTONE_SLAB = registerBlock("blackstone_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CALCITE_SLAB = registerBlock("calcite_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        TUFF_SLAB = registerBlock("tuff_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        DRIPSTONE_BLOCK_SLAB = registerBlock("dripstone_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        PRISMARINE_SLAB = registerBlock("prismarine_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        MAGMA_BLOCK_SLAB = registerBlock("magma_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        OBSIDIAN_SLAB = registerBlock("obsidian_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CRYING_OBSIDIAN_SLAB = registerBlock("crying_obsidian_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BUDDING_AMETHYST_SLAB = registerBlock("budding_amethyst_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BROWN_MUSHROOM_BLOCK_SLAB = registerBlock("brown_mushroom_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        RED_MUSHROOM_BLOCK_SLAB = registerBlock("red_mushroom_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        NETHER_WART_BLOCK_SLAB = registerBlock("nether_wart_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        WARPED_WART_BLOCK_SLAB = registerBlock("warped_wart_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        GLOWSTONE_SLAB = registerBlock("glowstone_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        SHROOMLIGHT_SLAB = registerBlock("shroomlight_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        DRIED_KELP_BLOCK_SLAB = registerBlock("dried_kelp_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        TUBE_CORAL_BLOCK_SLAB = registerBlock("tube_coral_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BRAIN_CORAL_BLOCK_SLAB = registerBlock("brain_coral_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BUBBLE_CORAL_BLOCK_SLAB = registerBlock("bubble_coral_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        FIRE_CORAL_BLOCK_SLAB = registerBlock("fire_coral_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        HORN_CORAL_BLOCK_SLAB = registerBlock("horn_coral_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        DEAD_TUBE_CORAL_BLOCK_SLAB = registerBlock("dead_tube_coral_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        DEAD_BRAIN_CORAL_BLOCK_SLAB = registerBlock("dead_brain_coral_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        DEAD_BUBBLE_CORAL_BLOCK_SLAB = registerBlock("dead_bubble_coral_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        DEAD_FIRE_CORAL_BLOCK_SLAB = registerBlock("dead_fire_coral_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        DEAD_HORN_CORAL_BLOCK_SLAB = registerBlock("dead_horn_coral_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        SPONGE_SLAB = registerBlock("sponge_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        WET_SPONGE_SLAB = registerBlock("wet_sponge_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        MELON_SLAB = registerBlock("melon_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        PUMPKIN_SLAB = registerBlock("pumpkin_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        HAY_BALE_SLAB = registerBlock("hay_bale_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        HONEYCOMB_BLOCK_SLAB = registerBlock("honeycomb_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        SLIME_BLOCK_SLAB = registerBlock("slime_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        HONEY_BLOCK_SLAB = registerBlock("honey_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        OCHRE_FROGLIGHT_SLAB = registerBlock("ochre_froglight_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        VERDANT_FROGLIGHT_SLAB = registerBlock("verdant_froglight_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        PEARLESCENT_FROGLIGHT_SLAB = registerBlock("pearlescent_froglight_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        SCULK_SLAB = registerBlock("sculk_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BEDROCK_SLAB = registerBlock("bedrock_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        OAK_LOG_SLAB = registerBlock("oak_log_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        OAK_WOOD_SLAB = registerBlock("oak_wood_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        STRIPPED_OAK_LOG_SLAB = registerBlock("stripped_oak_log_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        STRIPPED_OAK_WOOD_SLAB = registerBlock("stripped_oak_wood_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        SPRUCE_LOG_SLAB = registerBlock("spruce_log_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        SPRUCE_WOOD_SLAB = registerBlock("spruce_wood_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        STRIPPED_SPRUCE_LOG_SLAB = registerBlock("stripped_spruce_log_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        STRIPPED_SPRUCE_WOOD_SLAB = registerBlock("stripped_spruce_wood_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BIRCH_LOG_SLAB = registerBlock("birch_log_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BIRCH_WOOD_SLAB = registerBlock("birch_wood_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        STRIPPED_BIRCH_LOG_SLAB = registerBlock("stripped_birch_log_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        STRIPPED_BIRCH_WOOD_SLAB = registerBlock("stripped_birch_wood_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        JUNGLE_LOG_SLAB = registerBlock("jungle_log_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        JUNGLE_WOOD_SLAB = registerBlock("jungle_wood_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        STRIPPED_JUNGLE_LOG_SLAB = registerBlock("stripped_jungle_log_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        STRIPPED_JUNGLE_WOOD_SLAB = registerBlock("stripped_jungle_wood_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        ACACIA_LOG_SLAB = registerBlock("acacia_log_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        ACACIA_WOOD_SLAB = registerBlock("acacia_wood_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        STRIPPED_ACACIA_LOG_SLAB = registerBlock("stripped_acacia_log_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        STRIPPED_ACACIA_WOOD_SLAB = registerBlock("stripped_acacia_wood_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        DARK_OAK_LOG_SLAB = registerBlock("dark_oak_log_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        DARK_OAK_WOOD_SLAB = registerBlock("dark_oak_wood_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        STRIPPED_DARK_OAK_LOG_SLAB = registerBlock("stripped_dark_oak_log_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        STRIPPED_DARK_OAK_WOOD_SLAB = registerBlock("stripped_dark_oak_wood_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        MANGROVE_LOG_SLAB = registerBlock("mangrove_log_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        MANGROVE_WOOD_SLAB = registerBlock("mangrove_wood_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        STRIPPED_MANGROVE_LOG_SLAB = registerBlock("stripped_mangrove_log_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        STRIPPED_MANGROVE_WOOD_SLAB = registerBlock("stripped_mangrove_wood_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CHERRY_LOG_SLAB = registerBlock("cherry_log_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CHERRY_WOOD_SLAB = registerBlock("cherry_wood_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        STRIPPED_CHERRY_LOG_SLAB = registerBlock("stripped_cherry_log_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        STRIPPED_CHERRY_WOOD_SLAB = registerBlock("stripped_cherry_wood_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BAMBOO_BLOCK_SLAB = registerBlock("bamboo_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        STRIPPED_BAMBOO_BLOCK_SLAB = registerBlock("stripped_bamboo_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CRIMSON_STEM_SLAB = registerBlock("crimson_stem_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CRIMSON_HYPHAE_SLAB = registerBlock("crimson_hyphae_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        STRIPPED_CRIMSON_STEM_SLAB = registerBlock("stripped_crimson_stem_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        STRIPPED_CRIMSON_HYPHAE_SLAB = registerBlock("stripped_crimson_hyphae_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        WARPED_STEM_SLAB = registerBlock("warped_stem_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        WARPED_HYPHAE_SLAB = registerBlock("warped_hyphae_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        STRIPPED_WARPED_STEM_SLAB = registerBlock("stripped_warped_stem_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        STRIPPED_WARPED_HYPHAE_SLAB = registerBlock("stripped_warped_hyphae_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CRACKED_STONE_BRICKS_SLAB = registerBlock("cracked_stone_bricks_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CHISELED_STONE_BRICKS_SLAB = registerBlock("chiseled_stone_bricks_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        DEEPSLATE_SLAB = registerBlock("deepslate_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CHISELED_DEEPSLATE_SLAB = registerBlock("chiseled_deepslate_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CRACKED_DEEPSLATE_BRICKS_SLAB = registerBlock("cracked_deepslate_bricks_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CRACKED_DEEPSLATE_TILES_SLAB = registerBlock("cracked_deepslate_tiles_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        REINFORCED_DEEPSLATE_SLAB = registerBlock("reinforced_deepslate_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        PACKED_MUD_SLAB = registerBlock("packed_mud_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CHISELED_SANDSTONE_SLAB = registerBlock("chiseled_sandstone_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CHISELED_RED_SANDSTONE_SLAB = registerBlock("chiseled_red_sandstone_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        NETHERRACK_SLAB = registerBlock("netherrack_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CRACKED_NETHER_BRICKS_SLAB = registerBlock("cracked_nether_bricks_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CHISELED_NETHER_BRICKS_SLAB = registerBlock("chiseled_nether_bricks_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BASALT_SLAB = registerBlock("basalt_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        SMOOTH_BASALT_SLAB = registerBlock("smooth_basalt_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        POLISHED_BASALT_SLAB = registerBlock("polished_basalt_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        GILDED_BLACKSTONE_SLAB = registerBlock("gilded_blackstone_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CHISELED_POLISHED_BLACKSTONE_SLAB = registerBlock("chiseled_polished_blackstone_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CRACKED_POLISHED_BLACKSTONE_BRICKS_SLAB = registerBlock("cracked_polished_blackstone_bricks_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        END_STONE_SLAB = registerBlock("end_stone_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        PURPUR_PILLAR_SLAB = registerBlock("purpur_pillar_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        COAL_BLOCK_SLAB = registerBlock("coal_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        IRON_BLOCK_SLAB = registerBlock("iron_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        GOLD_BLOCK_SLAB = registerBlock("gold_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        REDSTONE_BLOCK_SLAB = registerBlock("redstone_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        EMERALD_BLOCK_SLAB = registerBlock("emerald_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        LAPIS_BLOCK_SLAB = registerBlock("lapis_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        DIAMOND_BLOCK_SLAB = registerBlock("diamond_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        NETHERITE_BLOCK_SLAB = registerBlock("netherite_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CHISELED_QUARTZ_BLOCK_SLAB = registerBlock("chiseled_quartz_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        QUARTZ_BRICKS_SLAB = registerBlock("quartz_bricks_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        QUARTZ_PILLAR_SLAB = registerBlock("quartz_pillar_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        AMETHYST_BLOCK_SLAB = registerBlock("amethyst_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        COPPER_BLOCK_SLAB = registerBlock("copper_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        EXPOSED_COPPER_BLOCK_SLAB = registerBlock("exposed_copper_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        WEATHERED_COPPER_BLOCK_SLAB = registerBlock("weathered_copper_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        OXIDIZED_COPPER_BLOCK_SLAB = registerBlock("oxidized_copper_block_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        WHITE_WOOL_SLAB = registerBlock("white_wool_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        LIGHT_GRAY_WOOL_SLAB = registerBlock("light_gray_wool_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        GRAY_WOOL_SLAB = registerBlock("gray_wool_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BLACK_WOOL_SLAB = registerBlock("black_wool_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BROWN_WOOL_SLAB = registerBlock("brown_wool_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        RED_WOOL_SLAB = registerBlock("red_wool_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        ORANGE_WOOL_SLAB = registerBlock("orange_wool_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        YELLOW_WOOL_SLAB = registerBlock("yellow_wool_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        LIME_WOOL_SLAB = registerBlock("lime_wool_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        GREEN_WOOL_SLAB = registerBlock("green_wool_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CYAN_WOOL_SLAB = registerBlock("cyan_wool_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        LIGHT_BLUE_WOOL_SLAB = registerBlock("light_blue_wool_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BLUE_WOOL_SLAB = registerBlock("blue_wool_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        PURPLE_WOOL_SLAB = registerBlock("purple_wool_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        MAGENTA_WOOL_SLAB = registerBlock("magenta_wool_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        PINK_WOOL_SLAB = registerBlock("pink_wool_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        TERRACOTTA_SLAB = registerBlock("terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        WHITE_TERRACOTTA_SLAB = registerBlock("white_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        LIGHT_GRAY_TERRACOTTA_SLAB = registerBlock("light_gray_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        GRAY_TERRACOTTA_SLAB = registerBlock("gray_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BLACK_TERRACOTTA_SLAB = registerBlock("black_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BROWN_TERRACOTTA_SLAB = registerBlock("brown_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        RED_TERRACOTTA_SLAB = registerBlock("red_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        ORANGE_TERRACOTTA_SLAB = registerBlock("orange_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        YELLOW_TERRACOTTA_SLAB = registerBlock("yellow_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        LIME_TERRACOTTA_SLAB = registerBlock("lime_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        GREEN_TERRACOTTA_SLAB = registerBlock("green_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CYAN_TERRACOTTA_SLAB = registerBlock("cyan_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        LIGHT_BLUE_TERRACOTTA_SLAB = registerBlock("light_blue_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BLUE_TERRACOTTA_SLAB = registerBlock("blue_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        PURPLE_TERRACOTTA_SLAB = registerBlock("purple_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        MAGENTA_TERRACOTTA_SLAB = registerBlock("magenta_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        PINK_TERRACOTTA_SLAB = registerBlock("pink_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        WHITE_CONCRETE_SLAB = registerBlock("white_concrete_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        LIGHT_GRAY_CONCRETE_SLAB = registerBlock("light_gray_concrete_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        GRAY_CONCRETE_SLAB = registerBlock("gray_concrete_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BLACK_CONCRETE_SLAB = registerBlock("black_concrete_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BROWN_CONCRETE_SLAB = registerBlock("brown_concrete_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        RED_CONCRETE_SLAB = registerBlock("red_concrete_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        ORANGE_CONCRETE_SLAB = registerBlock("orange_concrete_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        YELLOW_CONCRETE_SLAB = registerBlock("yellow_concrete_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        LIME_CONCRETE_SLAB = registerBlock("lime_concrete_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        GREEN_CONCRETE_SLAB = registerBlock("green_concrete_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CYAN_CONCRETE_SLAB = registerBlock("cyan_concrete_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        LIGHT_BLUE_CONCRETE_SLAB = registerBlock("light_blue_concrete_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BLUE_CONCRETE_SLAB = registerBlock("blue_concrete_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        PURPLE_CONCRETE_SLAB = registerBlock("purple_concrete_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        MAGENTA_CONCRETE_SLAB = registerBlock("magenta_concrete_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        PINK_CONCRETE_SLAB = registerBlock("pink_concrete_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        WHITE_CONCRETE_POWDER_SLAB = registerBlock("white_concrete_powder_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        LIGHT_GRAY_CONCRETE_POWDER_SLAB = registerBlock("light_gray_concrete_powder_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        GRAY_CONCRETE_POWDER_SLAB = registerBlock("gray_concrete_powder_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BLACK_CONCRETE_POWDER_SLAB = registerBlock("black_concrete_powder_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BROWN_CONCRETE_POWDER_SLAB = registerBlock("brown_concrete_powder_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        RED_CONCRETE_POWDER_SLAB = registerBlock("red_concrete_powder_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        ORANGE_CONCRETE_POWDER_SLAB = registerBlock("orange_concrete_powder_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        YELLOW_CONCRETE_POWDER_SLAB = registerBlock("yellow_concrete_powder_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        LIME_CONCRETE_POWDER_SLAB = registerBlock("lime_concrete_powder_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        GREEN_CONCRETE_POWDER_SLAB = registerBlock("green_concrete_powder_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CYAN_CONCRETE_POWDER_SLAB = registerBlock("cyan_concrete_powder_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        LIGHT_BLUE_CONCRETE_POWDER_SLAB = registerBlock("light_blue_concrete_powder_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BLUE_CONCRETE_POWDER_SLAB = registerBlock("blue_concrete_powder_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        PURPLE_CONCRETE_POWDER_SLAB = registerBlock("purple_concrete_powder_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        MAGENTA_CONCRETE_POWDER_SLAB = registerBlock("magenta_concrete_powder_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        PINK_CONCRETE_POWDER_SLAB = registerBlock("pink_concrete_powder_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        WHITE_GLAZED_TERRACOTTA_SLAB = registerBlock("white_glazed_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        LIGHT_GRAY_GLAZED_TERRACOTTA_SLAB = registerBlock("light_gray_glazed_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        GRAY_GLAZED_TERRACOTTA_SLAB = registerBlock("gray_glazed_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BLACK_GLAZED_TERRACOTTA_SLAB = registerBlock("black_glazed_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BROWN_GLAZED_TERRACOTTA_SLAB = registerBlock("brown_glazed_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        RED_GLAZED_TERRACOTTA_SLAB = registerBlock("red_glazed_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        ORANGE_GLAZED_TERRACOTTA_SLAB = registerBlock("orange_glazed_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        YELLOW_GLAZED_TERRACOTTA_SLAB = registerBlock("yellow_glazed_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        LIME_GLAZED_TERRACOTTA_SLAB = registerBlock("lime_glazed_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        GREEN_GLAZED_TERRACOTTA_SLAB = registerBlock("green_glazed_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        CYAN_GLAZED_TERRACOTTA_SLAB = registerBlock("cyan_glazed_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        LIGHT_BLUE_GLAZED_TERRACOTTA_SLAB = registerBlock("light_blue_glazed_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        BLUE_GLAZED_TERRACOTTA_SLAB = registerBlock("blue_glazed_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        PURPLE_GLAZED_TERRACOTTA_SLAB = registerBlock("purple_glazed_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        MAGENTA_GLAZED_TERRACOTTA_SLAB = registerBlock("magenta_glazed_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));
        PINK_GLAZED_TERRACOTTA_SLAB = registerBlock("pink_glazed_terracotta_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).instrument(NoteBlockInstrument.BASS).strength(2.0F, 3.0F).sound(SoundType.WOOD).ignitedByLava()));

    }

    private static Block registerBlock(String name, Block block) {
        registerBlockItem(name, block);
        return Registry.register(BuiltInRegistries.BLOCK, ResourceLocation.fromNamespaceAndPath(Constants.MOD_ID, name), block);
    }

    private static Item registerBlockItem(String name, Block block) {
        return Registry.register(BuiltInRegistries.ITEM, ResourceLocation.fromNamespaceAndPath(Constants.MOD_ID, name),
                new BlockItem(block, new Item.Properties()));
    }

    public static void registerModBlocks() {
        Constants.LOG.info("Registering ModBlocks for " + Constants.MOD_ID);
    }
}
